services:
 frontend:
  build:
   context: ./integradorG5Front/
   tags:
    - "v1.0"
    - "ghcr.io/luisdelgado-ld/frontend:v1.0"
    - "ghcr.io/luisdelgado-ld/frontend:latest"
  image: ghcr.io/luisdelgado-ld/frontend:latest
  restart:
    always
  ports:
   - 80:80
  networks:
   default:
    aliases:
     - proyectointegrador-frontend
     - frontend
 backend:
  build:
   context: ./integradorG5Back/
   tags:
    - "v1.0"
    - "ghcr.io/luisdelgado-ld/backend:v1.0"
    - "ghcr.io/luisdelgado-ld/backend:latest"
  image: ghcr.io/luisdelgado-ld/backend:latest
  restart:
    always
  ports:
   - 8080:8080
  networks:
   default:
    aliases:
     - backend
     - proyectointegrador-backend
 database:
  image: mysql:9.2.0
  environment:
   - MYSQL_USER=My_own_USER
   - MYSQL_PASSWORD=ds8adskjl21edas9
   - MYSQL_ROOT_PASSWORD=123456789
   - MYSQL_DATABASE=pet_paradise
  ports:
   - 3310:3306
  restart:
   always
  volumes:
   - db:/var/lib/mysql
  networks:
   default:
    aliases:
     - database
     - proyectointegrador-database
 ddns:
  image: ghcr.io/noipcom/noip-duc:3.2.0
  restart:
   always
  environment:
   - NOIP_USERNAME=53a2ake
   - NOIP_PASSWORD=2AALUKECTbpA
   - NOIP_HOSTNAMES=petparadise.sytes.net

volumes:
 db:
