services:
 frontend:
  build:
   context: ./integradorG5Front/
   tags:
    - "v0.5"
    - "ghcr.io/luisdelgado-ld/frontend:v0.5"
    - "ghcr.io/luisdelgado-ld/frontend:latest"
  image: ghcr.io/luisdelgado-ld/frontend:latest
  ports:
   - 8585:5173
  networks:
   default:
    aliases:
     - proyectointegrador-frontend
 backend:
  build:
   context: ./integradorG5Back/
   tags:
    - "v0.5"
    - "ghcr.io/luisdelgado-ld/backend:v0.5"
    - "ghcr.io/luisdelgado-ld/backend:latest"
  image: ghcr.io/luisdelgado-ld/backend:latest
  ports:
   - 8586:8080
 database:
  image: mysql:9.2.0
  environment:
   - MYSQL_USER=My_own_USER
   - MYSQL_PASSWORD=ds8adskjl21edas9
   - MYSQL_ROOT_PASSWORD=123456789
   - MYSQL_DATABASE=pet_paradise
  ports:
   - 3310:3306  
  networks:
   default:
    aliases:
     - database   
     - proyectointegrador-database
