services:
 certbot:
  image: certbot/certbot:latest
  volumes:
   - www:/var/www/certbot/:rw
   - cert:/etc/letsencrypt/:rw
 frontend:
  build:
   context: ./integradorG5Front/
   tags:
    - "ghcr.io/luisdelgado-ld/frontend:v1.0"
    - "ghcr.io/luisdelgado-ld/frontend:latest"
  image: ghcr.io/luisdelgado-ld/frontend:latest
  restart:
    always
  ports:
   - 80:80
   - 443:443
  volumes:
   - www:/var/www/certbot/:ro
   - cert:/etc/nginx/ssl/:ro
  networks:
   default:
    aliases:
     - proyectointegrador-frontend
     - frontend
  environment:
   - URL_BACK=http://backend:8080/api/
  healthcheck:
   test: ["CMD","curl", "http://localhost"]
   timeout: 5s
   retries: 3
 backend:
  build:
   context: ./integradorG5Back/
   tags:
    - "ghcr.io/luisdelgado-ld/backend:v1.0"
    - "ghcr.io/luisdelgado-ld/backend:latest"
  image: ghcr.io/luisdelgado-ld/backend:latest
  environment:
   - DB_URL=jdbc:mysql://database/pet_paradise
   - DB_USER=My_own_USER
   - DB_PASS=ds8adskjl21edas9
   - CLOUD_NAME=f,sajdlaksd
   - CLOUD_KEY=8293719231
   - CLOUD_SECRET=asdhqwked
  restart:
    always
  ports:
   - 8080:8080
  networks:
   default:
    aliases:
     - backend
     - proyectointegrador-backend
  healthcheck:
   test: ["CMD","wget", "http://localhost:8080/api/habitaciones/all", "-O", "/dev/null"]
   timeout: 5s
   retries: 3
  depends_on:
   database:
    condition: service_healthy
 database:
  build:
   context: ./database/
   tags:
    - "ghcr.io/luisdelgado-ld/database:v1.0"
    - "ghcr.io/luisdelgado-ld/database:latest"
  image: ghcr.io/luisdelgado-ld/database:latest
  environment:
   - MYSQL_USER=My_own_USER
   - MYSQL_PASSWORD=ds8adskjl21edas9
   - MYSQL_ROOT_PASSWORD=123456789
   - MYSQL_DATABASE=pet_paradise
  ports:
   - 3306:3306
  restart:
   always
  volumes:
   - db:/var/lib/mysql
  networks:
   default:
    aliases:
     - database
     - proyectointegrador-database
  healthcheck:
   test: ["CMD","mysqladmin","ping","-h","localhost"]
   timeout: 5s
   retries: 3
 ddns:
  image: ghcr.io/noipcom/noip-duc:3.2.0
  restart:
   always
  environment:
   - NOIP_USERNAME=53a2ake
   - NOIP_PASSWORD=2AALUKECTbpA
   - NOIP_HOSTNAMES=petparadise.sytes.net

volumes:
 db:
 www:
 cert:

